/**
 * Admin: Receipt Maker — Generate and share receipts with multi-user targeting
 * File: apps/mobile/app/admin/receipt-maker.tsx
 */
import React, { useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  FlatList,
  Linking,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  Share,
} from "react-native";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";

type AdminUser = {
  id: string;
  fullName?: string;
  email?: string;
  phone?: string;
  status?: string;
};

export default function ReceiptMakerScreen() {
  const qc = useQueryClient();
  const [receiptNum] = useState(() => {
    const timestamp = Date.now().toString().slice(-6);
    const random = Math.floor(Math.random() * 1000)
      .toString()
      .padStart(3, "0");
    return `RCP-${timestamp}${random}`;
  });

  const [tab, setTab] = useState<"compose" | "preview">("compose");
  const [header, setHeader] = useState("Receipt Confirmation");
  const [bodyText, setBodyText] = useState("");
  const [selectedUserIds, setSelectedUserIds] = useState<Set<string>>(new Set());
  const [userSearch, setUserSearch] = useState("");
  const [sendNotification, setSendNotification] = useState(false);
  const [notificationTitle, setNotificationTitle] = useState("New Receipt");
  const [notificationBody, setNotificationBody] = useState("Receipt generated for you");
  const [sending, setSending] = useState(false);

  const { data: users = [], isLoading: usersLoading } = useQuery<AdminUser[]>({
    queryKey: ["admin-receipt-users"],
    queryFn: () =>
      api
        .get("/users?status=APPROVED&limit=100")
        .then((r) => r.data.data?.items ?? []),
  });

  const filteredUsers = useMemo(() => {
    const q = userSearch.trim().toLowerCase();
    if (!q) return users.slice(0, 50);
    return users.filter((u) => {
      const name = (u.fullName ?? "").toLowerCase();
      const email = (u.email ?? "").toLowerCase();
      const phone = (u.phone ?? "").toLowerCase();
      return name.includes(q) || email.includes(q) || phone.includes(q);
    });
  }, [users, userSearch]);

  const recipientCount = selectedUserIds.size;

  // Format receipt for display
  const receiptContent = generateReceiptText(receiptNum, header, bodyText);

  // Generate WhatsApp shareable text
  function generateReceiptText(num: string, headerText: string, body: string): string {
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-IN");
    const timeStr = now.toLocaleTimeString("en-IN");
    return `
${"═".repeat(40)}
           RECEIPT
${"═".repeat(40)}

Receipt #: ${num}
Date: ${dateStr}
Time: ${timeStr}

${headerText}

${body}

${"═".repeat(40)}
Generated by SCJYM Admin
${"═".repeat(40)}
    `.trim();
  }

  async function shareViaWhatsApp(userPhone?: string) {
    if (!bodyText.trim()) {
      Alert.alert("Validation", "Please add message to receipt body");
      return;
    }

    const message = receiptContent;
    const encodedMsg = encodeURIComponent(message);

    if (userPhone) {
      const cleanPhone = userPhone.replace(/\D/g, "");
      const whatsappUrl =
        Platform.OS === "ios"
          ? `whatsapp://send?phone=91${cleanPhone}&text=${encodedMsg}`
          : `https://wa.me/91${cleanPhone}?text=${encodedMsg}`;

      try {
        const supported = await Linking.canOpenURL(whatsappUrl);
        if (supported) {
          await Linking.openURL(whatsappUrl);
        } else {
          Alert.alert("Error", "WhatsApp not installed on this device");
        }
      } catch (e) {
        Alert.alert("Error", "Could not open WhatsApp");
      }
    } else {
      try {
        await Share.share({
          message: receiptContent,
          title: `Receipt ${receiptNum}`,
        });
      } catch (e) {
        Alert.alert("Error", "Could not share receipt");
      }
    }
  }

  const sendReceiptMut = useMutation({
    mutationFn: async () => {
      if (!bodyText.trim()) throw new Error("Receipt body is required");
      if (selectedUserIds.size === 0) throw new Error("Select at least one recipient");

      const targetUserIds = Array.from(selectedUserIds);
      const receipt = {
        receiptNum,
        header,
        body: bodyText,
        generatedAt: new Date().toISOString(),
        recipients: targetUserIds,
      };

      // If sending notification, include receipt in push payload
      if (sendNotification) {
        return api.post("/admin/notifications/push", {
          title: notificationTitle.trim() || "New Receipt",
          body: notificationBody.trim() || receiptContent.split("\n")[3],
          targetUserIds,
          receiptData: receipt,
        });
      }

      // Otherwise just store receipt
      return api.post("/admin/receipts", receipt);
    },
    onSuccess: (response) => {
      Alert.alert("Success", `Receipt sent to ${selectedUserIds.size} recipient(s)`);
      setBodyText("");
      setSelectedUserIds(new Set());
      setHeader("Receipt Confirmation");
      setSendNotification(false);
      qc.invalidateQueries({ queryKey: ["admin-receipt-users"] });
    },
    onError: (e: any) => {
      Alert.alert("Error", e?.response?.data?.error?.message || e.message);
    },
  });

  return (
    <View style={styles.root}>
      {/* Tabs */}
      <View style={styles.tabBar}>
        <TouchableOpacity
          style={[styles.tab, tab === "compose" && styles.tabActive]}
          onPress={() => setTab("compose")}
        >
          <Text style={[styles.tabText, tab === "compose" && styles.tabTextActive]}>
            📝 Compose
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.tab, tab === "preview" && styles.tabActive]}
          onPress={() => setTab("preview")}
        >
          <Text style={[styles.tabText, tab === "preview" && styles.tabTextActive]}>
            👁️ Preview
          </Text>
        </TouchableOpacity>
      </View>

      {/* Compose Tab */}
      {tab === "compose" && (
        <ScrollView contentContainerStyle={styles.body}>
          {/* Receipt Metadata */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Receipt Info</Text>
            <View style={styles.infoBox}>
              <Text style={styles.infoLabel}>Receipt #</Text>
              <Text style={styles.infoValue}>{receiptNum}</Text>
            </View>
          </View>

          {/* Header */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Header Message</Text>
            <TextInput
              style={styles.input}
              value={header}
              onChangeText={setHeader}
              placeholder="e.g., Receipt Confirmation"
              multiline
              numberOfLines={2}
            />
          </View>

          {/* Body */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Receipt Body</Text>
            <TextInput
              style={[styles.input, styles.inputLarge]}
              value={bodyText}
              onChangeText={setBodyText}
              placeholder={
                "Enter receipt details:\n\nOrder ID: 12345\nAmount: ₹500\nPayment Status: Completed\nItems: ...\n\nThank you for your purchase!"
              }
              multiline
              numberOfLines={8}
            />
          </View>

          {/* Recipients */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>
              Recipients ({recipientCount} selected)
            </Text>
            <TextInput
              style={styles.searchInput}
              placeholder="Search by name, email, or phone..."
              value={userSearch}
              onChangeText={setUserSearch}
            />
            {usersLoading ? (
              <ActivityIndicator color="#1a56db" />
            ) : (
              <FlatList
                data={filteredUsers}
                keyExtractor={(u) => u.id}
                scrollEnabled={false}
                renderItem={({ item: u }) => (
                  <TouchableOpacity
                    style={styles.userItem}
                    onPress={() => {
                      const newSet = new Set(selectedUserIds);
                      if (newSet.has(u.id)) {
                        newSet.delete(u.id);
                      } else {
                        newSet.add(u.id);
                      }
                      setSelectedUserIds(newSet);
                    }}
                  >
                    <View
                      style={[
                        styles.checkbox,
                        selectedUserIds.has(u.id) && styles.checkboxActive,
                      ]}
                    >
                      {selectedUserIds.has(u.id) && (
                        <Text style={styles.checkmark}>✓</Text>
                      )}
                    </View>
                    <View style={styles.userInfo}>
                      <Text style={styles.userName}>{u.fullName || "Unknown"}</Text>
                      <Text style={styles.userMeta}>
                        {u.email}
                        {u.phone ? ` • ${u.phone}` : ""}
                      </Text>
                    </View>
                  </TouchableOpacity>
                )}
              />
            )}
          </View>

          {/* Notification Option */}
          <View style={styles.section}>
            <View style={styles.switchRow}>
              <Text style={styles.sectionTitle}>Send as Push Notification</Text>
              <TouchableOpacity
                style={[
                  styles.toggle,
                  sendNotification && styles.toggleActive,
                ]}
                onPress={() => setSendNotification(!sendNotification)}
              >
                <View
                  style={[
                    styles.toggleBall,
                    sendNotification && styles.toggleBallActive,
                  ]}
                />
              </TouchableOpacity>
            </View>

            {sendNotification && (
              <>
                <TextInput
                  style={styles.input}
                  value={notificationTitle}
                  onChangeText={setNotificationTitle}
                  placeholder="Notification title"
                />
                <TextInput
                  style={[styles.input, { marginTop: 8 }]}
                  value={notificationBody}
                  onChangeText={setNotificationBody}
                  placeholder="Notification body"
                  multiline
                  numberOfLines={2}
                />
              </>
            )}
          </View>

          {/* Action Buttons */}
          <View style={styles.actionRow}>
            <TouchableOpacity
              style={[styles.btn, styles.btnSecondary]}
              onPress={() => shareViaWhatsApp()}
            >
              <Text style={styles.btnSecondaryText}>📱 Share Text</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.btn, styles.btnPrimary, sending && { opacity: 0.7 }]}
              onPress={() => sendReceiptMut.mutate()}
              disabled={sending}
            >
              {sending ? (
                <ActivityIndicator color="#fff" size="small" />
              ) : (
                <Text style={styles.btnText}>
                  {sendNotification ? "📤 Send + Notify" : "📤 Send Receipts"}
                </Text>
              )}
            </TouchableOpacity>
          </View>
        </ScrollView>
      )}

      {/* Preview Tab */}
      {tab === "preview" && (
        <ScrollView contentContainerStyle={styles.preview}>
          <View style={styles.receiptPreview}>
            <Text style={styles.receiptText}>{receiptContent}</Text>
          </View>
          <TouchableOpacity
            style={[styles.btn, styles.btnPrimary, { marginTop: 16 }]}
            onPress={() => shareViaWhatsApp()}
          >
            <Text style={styles.btnText}>📱 Share via WhatsApp</Text>
          </TouchableOpacity>
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f9fafb" },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  tab: { flex: 1, paddingVertical: 14, alignItems: "center", borderBottomWidth: 3, borderBottomColor: "transparent" },
  tabActive: { borderBottomColor: "#1a56db" },
  tabText: { fontSize: 14, fontWeight: "600", color: "#9ca3af" },
  tabTextActive: { color: "#1a56db" },
  body: { padding: 16, paddingBottom: 40 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: "700", color: "#111827", marginBottom: 8 },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: "#111827",
  },
  inputLarge: { minHeight: 100 },
  infoBox: { backgroundColor: "#f3f4f6", borderRadius: 10, padding: 12 },
  infoLabel: { fontSize: 12, color: "#9ca3af", fontWeight: "600" },
  infoValue: { fontSize: 18, fontWeight: "700", color: "#1a56db", marginTop: 4 },
  searchInput: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: "#111827",
    marginBottom: 12,
  },
  userItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxActive: { backgroundColor: "#1a56db", borderColor: "#1a56db" },
  checkmark: { color: "#fff", fontSize: 12, fontWeight: "700" },
  userInfo: { flex: 1 },
  userName: { fontSize: 14, fontWeight: "600", color: "#111827" },
  userMeta: { fontSize: 12, color: "#9ca3af", marginTop: 2 },
  switchRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  toggle: {
    width: 50,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#d1d5db",
    padding: 2,
    justifyContent: "center",
  },
  toggleActive: { backgroundColor: "#1a56db" },
  toggleBall: { width: 24, height: 24, borderRadius: 12, backgroundColor: "#fff", alignSelf: "flex-start" },
  toggleBallActive: { alignSelf: "flex-end" },
  actionRow: { flexDirection: "row", gap: 12 },
  btn: { flex: 1, borderRadius: 10, paddingVertical: 12, alignItems: "center" },
  btnPrimary: { backgroundColor: "#1a56db" },
  btnSecondary: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e5e7eb" },
  btnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  btnSecondaryText: { color: "#1a56db", fontWeight: "700", fontSize: 14 },
  preview: { padding: 16, paddingBottom: 40 },
  receiptPreview: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  receiptText: {
    fontFamily: Platform.OS === "ios" ? "Courier New" : "monospace",
    fontSize: 12,
    color: "#111827",
    lineHeight: 18,
  },
});
